# Generated by Django 5.0 on 2024-01-01 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("health", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuarantineRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("Sick Cow", "Sick Cow"),
                            ("Bought Cow", "Bought Cow"),
                            ("New Cow", "New Cow"),
                            ("Calving", "Calving"),
                        ],
                        max_length=35,
                    ),
                ),
                ("start_date", models.DateField(auto_now_add=True)),
                ("end_date", models.DateField(null=True)),
                ("notes", models.TextField(max_length=100, null=True)),
                (
                    "cow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quarantine_records",
                        to="core.cow",
                    ),
                ),
            ],
            options={
                "get_latest_by": "-start_date",
            },
        ),
    ]
